import abc
from typing import List
from uuid import UUID
from app.domain.models import AuditLog
from app.domain.repositories.base import IRepository


class IAuditLogRepository(IRepository[AuditLog], abc.ABC):
    @abc.abstractmethod
    def get_by_user_id(self, user_id: UUID, limit: int = 100) -> List[AuditLog]:
        """Fetch audit logs generated by a specific user profile."""
        pass
